min_areas:
  red: 3000
  green: 1000
  blue: 1000

video:
  trackbar: false
  save: false
  log_values: false
  get_gif: false 
  input_dir: input_videos/
  input_file: 500_245C_2.mp4
  output_dir: output_videos/
  output_name: 500_245C_2.mp4
  log_dir: logs/
  plot: false
  excel: false

mask: # HSV
  red:
    lower: [255, 0, 0]
    upper: [255, 255, 0]
  green:
    lower: [0, 255, 0]
    upper: [0, 200, 255]
  blue:
    lower: [0, 255, 255]
    upper: [255, 0, 4]

# video initial
# scale_roi:
#   x: 750
#   y: 25
#   w: 100
#   h: 610

# video 2.1 and 3.3
scale_roi:
  x: 930
  y: 25
  w: 100
  h: 750

pins_roi: # 250 pixels = 10 cm
  x: 220
  y: 0
  w: 250
  h: 170


shear_scale_color: 'shear_scale.png'

color_order: #RGB
  - (251,0,1)
  - (250,80,0)
  - (248,166,0)
  - (255,243,0)
  - (179,254,0)
  - (101,252,0)
  - (16,253,0)
  - (0,255,63)
  - (0,255,147)
  - (0,254,222)
  - (0,199,251)
  - (0,113,248)
  - (0,33,252)
  - (42,0,248)
  - (126,0,253)
  - (204,0,253)
